### PR TITLE
0.6.0

### PR DESCRIPTION
**Pull request by mikaoj**
* New version of protocol for communication between phone reader
* Reworked logic for restarting service

### CODE REVIEW

**Review by ce07c3 — COMMENTED** [review]
Perhaps we could add a changelog, or maybe that would be part of the releases feature here on GH?

**Comment by ce07c3** [comment]
> Like this? https://github.com/kisi-inc/kisi-ios-st2u-framework/releases

Yes, that's great.

**Comment by ce07c3** [comment]
Do you want me to review or @agap?

**Comment by mikaoj** [comment]
The code in the private repo is already reviewed...this is the public repo with just the binary. I don't expect anyone to review that. 🤖 
It's tagged as pre-release as of now...gonna be testing it this week before I merge / make it official.

**Pull request merged**
